config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :dashboard
  resources :tasks

  devise_for :users
  get 'pages/home'

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects.all
#    @project = 
    @tasks = Task.all
    @task = Task.new
    #@project = Project.find(params[:project_id])
    #@task = @project.tasks.build(task_description)

    render 'dashboard'
  end

  private
    def task_description
      params.require(:task).permit(:description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @projects = current_user.projects.all
    @project = current_user.projects.new

    render 'index'
    #respond_with(@projects)
  end

  def show
    #respond_with(@project)
  end

  #def new
    #@project = Project.new
    #respond_with(@project)
  #end

  def edit
    @project = Project.find(params[:id])
    render :edit
  end

  def create
    @project = current_user.projects.new(project_params)
    @project.save

    if @project.save
      redirect_to projects_path
    else
      render 'index'
    end
    #respond_with(@project)
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
    #respond_with(@project)
  end

  def destroy
    @project.destroy
    
    redirect_to projects_path
    #respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @projects = current_user.projects.all
    @task = Task.new(task_params)
    @task.save

    redirect_to dashboard_index_path
    #render 'dashboard/dashboard'
  end

  def destroy
    @task.destroy
    
    redirect_to dashboard_index_path
    #respond_with(@project)
  end

  private
    def task_params
      params.require(:task).permit(:project_id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboard/dashboard.html.erb
<%= render 'pages/nav' %>

<!-- <p id="notice"><%= notice %></p> -->

<div class="dashboard main">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 activity-form">
        <!--form class="row"-->
<!--           <div class="form-group col-sm-3">
            <select class="form-control">
              <% @projects.each do |project| %>
                <option><%= project.name %></option>
              <% end %>
            </select>
          </div> -->
          <%= form_for(@task) do |f| %>

            <div class="form-group col-sm-3">
              <%= f.select :project_id, @projects.map{ |p| [p.name, p.id] }, {}, class: "form-control" %>
            </div>

            <div class="form-group col-sm-8">
              <%= f.text_field :description, class: "form-control", placeholder: "¿En qué estás trabajando?" %>
              <!--input class="form-control" placeholder="¿En qué estás trabajando?" type="text" /-->
            </div>
            <div class="col-sm-1">
              <%= f.submit "Start", class: "btn btn-success", method: "create" %>
              <!--input class="btn btn-success" type="submit" value="Start" /-->
            </div>
          <% end %>
        <!--/form-->
      </div>
    </div>

    <div class="row">
      <table class="table activities-list">
        <thead>
          <tr>
            <th>Project</th>
            <th>Description</th>
            <th class="text-center">Time</th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <% project.tasks.each do |task| %>
              <tr>
                <td><%= project.name %></td>
                <td><%= task.description %></td>
                <td><%= task.time %></td>
                
              </tr>
            <% end %>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_nav.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TimeApp', pages_home_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <% if current_page?(dashboard_index_path) %>
            <li class= "active">
          <% else %>
            <li>
          <% end %>
            <%= link_to "Dashboard", dashboard_index_path %> <!--, class: ("active" if current_page?(dashboard_index_path)) %>
            <!--a href="dashboard.html">Dashboard</a-->
          </li>
          <% if current_page?(projects_path) %>
            <li class= "active">
          <% else %>
            <li>
          <% end %>
          <!--li class: ("active" if current_page?(projects_path))%>-->
            <%= link_to "Projects", projects_path %>
            <!-- class="active" a href="projects.html">Projects</a-->
          </li>
        </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
          <!--a href="signup.html">Sign Up</a>
          <a href="login.html">Log In</a></li-->
      </ul>
    </div>
  </div>
</nav>

<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

app/views/pages/home.html.erb
<%= render 'nav' %>

<div class="home">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <h1><span class="glyphicon glyphicon-time"></span> The Time Tracking App</h1>
        <p class="subtitle">Time tracking has never been this easy ... until now!</p>
        <div class="call-to-action">
          <% if user_signed_in? %>
            Go to<%= link_to "dashboard", dashboard_index_path %> to see your activies
          <% else %>
            <%= link_to "Sign up now", new_user_registration_path, class: "btn btn-default btn-lg" %>
            <%= link_to "... or Log in", new_user_session_path, class: "btn btn-lg" %>
          <% end %>
          <!--a class="btn btn-default btn-lg" href="singup.html">Sign up now</a>
          <a class="btn btn-lg" href="signup.html">... or Log in</a-->
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container cite">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h2>Our customers love us!</h2>
      <p>Or they will ... when we get them.</p>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

    <%= f.submit class: "btn btn-primary"%>
  </div>

<% end %>

<!--link_to "Ver", product_path(@product)
redirect_to prodcut_path @product

app/views/projects/_modal.html.erb
<div id="project-content-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">×</span><span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title"><%= title %></h4>
      </div>

      
        <div class="modal-body">
          <%= render 'form' %>
        </div>

          
    </div><!-- .modal-content -->
  </div><!-- .modal-dialog -->
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.js.erb
$("<%= j render partial: 'modal', locals: { title: 'Editing Project' } %>").modal();

app/views/projects/index.html.erb
<%= render 'pages/nav' %>

<!-- <p id="notice"><%= notice %></p> -->

<div class="projects main">
  <div class="container">
    <div class="row text-right">
      <%= link_to 'New Project', projects_path, remote: true, class: "btn btn-primary"  %>
      <!--a class="btn btn-primary" data-toggle="modal" href="#project-content-modal">New Project</a-->
    </div>
    <div class="row">
      <div class="col-sm-12">
        <table class="table projects-list">
          <thead>
            <tr>
              <th>Name</th>
              <th>Time</th>
              <th></th>
            </tr>
          </thead>
          <tbody>

            <% @projects.each do |project| %>
              <tr>
                <td><%= project.name %></td>
                <td><%= project.time %></td>
                <!--td><%= link_to 'Show', project %></td-->
                <td class="text-right">
                  <%= link_to 'Editar', edit_project_path(project), remote: true, class: "glyphicon glyphicon-edit" %>
                  <%= link_to 'Eliminar', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %>
                </td>
                
              </tr>
            <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.js.erb
$("<%= j render partial: 'modal', locals: { title: 'New Project' } %>").modal();

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>